version: '3.3'

services:
  database:
    container_name: postgres_db
    image: postgres:15
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=irrigation_system_design
    ports:
      - 5432:5432


# to run
# sudo docker-compose up