name: BeforeMerge

on:
  pull_request:
    branches: [ "main" ]

jobs:

  continuous-integration-before-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and Run Tests
        run: pytest

      - name: Create Zipfile archive of Dependencies
        run: |
          cd venv/lib/python3.8/site-packages
          zip -r9 ../../../../api.zip .

      - name: Add App to Zipfile
        run: cd irrigation_design_system_backend && zip -g ../api.zip -r .

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip
